pipeline{
    agent any
    stages{
        stage('Front-end'){
            steps{
                echo 'Hello-World!'
            }
        }
        stage('Database'){
            steps{
                echo 'Working on Data-base'
            }
        }
        stage('Backend'){
            steps{
                echo 'Welcome to java backend'
            }
        }
    }
}